model: yolov8n-seg.pt
data: configs/dataset.yaml
project: runs
name: defect_poc_cpu_smoke
epochs: 5
imgsz: 640
batch: 2
device: cpu
workers: 0
patience: 5
pretrained: true
optimizer: auto
seed: 42
hsv_h: 0.015
hsv_s: 0.4
hsv_v: 0.4
degrees: 4.0
translate: 0.08
scale: 0.2
perspective: 0.001
fliplr: 0.5
mosaic: 0.2
copy_paste: 0.0
export_onnx: false
